name: google_mobile_ads_demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  after_layout: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.3.0
  linter: ^1.30.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true